title: "GICV-ESPOCH"
name: "GICV-ESPOCH"
...

author:
  name: "GICV–ESPOCH"
  avatar: "/assets/images/espoch.jpeg"
  bio: "Grupo de Investigación en Ciencias Veterinarias"
  location: "Riobamba, Ecuador"
  email: "pamela.vinueza@espoch.edu.ec"
  links:
    - label: "ESPOCH"
      icon: "fas fa-university"
      url: "https://www.espoch.edu.ec"
    - label: "Email"
      icon: "fas fa-envelope"
      url: "mailto:pamela.vinueza@espoch.edu.ec"
    - label: "Google Scholar"
      icon: "fas fa-graduation-cap"
      url: "https://scholar.google.com/citations?user=eZFh3SwAAAAJ&hl=es"
    - label: "ResearchGate"
      icon: "fab fa-researchgate"
      url: "https://www.researchgate.net/profile/Pamela-Vinueza-Veloz"
    - label: "Instagram"
      icon: "fab fa-instagram"
      url: "https://www.instagram.com/grupo_gicv_espoch"
